<:cache duration=10m:>
<P>
<A NAME="linuxcom"><B>Headlines from <A HREF="http://www.linux.com">Linux.com</A></b></A>

<:try:>
<:datacomp headlines dcomps/linuxcom.pydcmp cache=yes:>

<font size=-1>
<ul>
<:for `headlines` head:>
<li>
<A HREF="<:val `head.url`:>"><:val `head.title` fmt=htmlquote:></a>
<br> <:val `head.description`:>
</li>
<:/for:>
</ul>
</font>
<:except:>
Linux.com headlines not available
<:cache duration=0m:>
<:/try:>
