<table>
  <form method="POST" action=<:val `action`:>>
    <tr>
      <td colspan="2"><b><:val `title`:></b></td>
    </tr>
    <tr>
      <td>username: </td><td><input type="text" name="username" size="35" /></td>
    </tr>
    <tr>
      <td>password:</td><td><input type="password" name="password" size="35" /></td>
    </tr>
    <tr>
      <td colspan="2"><input type="submit" value="login" /></td>
    </tr>
    <:hidden vals=`vals`:>
  </form>
</table>
