<html>
<head>
<:default subj "":>
<link rel="SHORTCUT ICON" href="favicon.ico">
<:if `subj`:>
<title>SkunkWEB | <:val `subj`:></title>
<:else:>
<title>SkunkWEB</title>
<:/if:>
<link rel="stylesheet" href="styles/sWEB.css" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<!-- start rollover goodies -->
<script language="JavaScript">
<!--

function newImage(arg) {
    if (document.images) {
	rslt = new Image();
	rslt.src = arg;
	return rslt;
    }
}

function changeImages() {
    if (document.images && (preloadFlag == true)) {
	for (var i=0; i<changeImages.arguments.length; i+=2) {
	document[changeImages.arguments[i]].src = changeImages.arguments[i+1];
        }
    }
}

var preloadFlag = false;
function preloadImages() {
    if (document.images) {
        selecto_05_over = newImage("images/selecto_05-over.gif");
	selecto_09_over = newImage("images/selecto_09-over.gif");
	selecto_13_selecto_09_over = newImage("images/selecto_13-selecto_09_over.gif");
	selecto_13_over = newImage("images/selecto_13-over.gif");
	selecto_17_over = newImage("images/selecto_17-over.gif");
	selecto_21_selecto_17_over = newImage("images/selecto_21-selecto_17_over.gif");
	selecto_21_over = newImage("images/selecto_21-over.gif");
	selecto_25_selecto_21_over = newImage("images/selecto_25-selecto_21_over.gif");
	selecto_25_over = newImage("images/selecto_25-over.gif");
	selecto_29_selecto_25_over = newImage("images/selecto_29-selecto_25_over.gif");
	selecto_29_over = newImage("images/selecto_29-over.gif");
	selecto_33_selecto_29_over = newImage("images/selecto_33-selecto_29_over.gif");
	selecto_33_over = newImage("images/selecto_33-over.gif");
	selecto_33_selecto_37_over = newImage("images/selecto_33-selecto_37_over.gif");
	selecto_37_over = newImage("images/selecto_37-over.gif");
	preloadFlag = true;
    }
}

// -->
</script>
<!-- end preload script -->
</head>
<body bgcolor=#FFFFFF onload="preloadImages();" link="#008800" alink="yellow" text="#202020" vlink="#008800">
<!-- end rollover goodies -->
<table align="left" bgcolor="#008800" width="100%" cellspacing="0" cellpadding="0" border="0" cols="*,100,*">
 <tr>
  <td colspan="2" bgcolor="#008800">
   <a href="http://skunkweb.sourceforge.net">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
     <tr>
      <td><a href="http://skunkweb.sourceforge.net/"><img src="images/WEB400green.gif" width="300" height="86" border="0" alt="SkunkWEB"></a></td>
      <td align="right"><img src="images/skunkWEB1_04.gif" width=171 height=86 border="0" alt="- smell the power!"></td>
     </tr>
    </table>
   </a></td>
 </tr>
 <tr>
 <td valign="top" width="100" bgcolor="white"><a href="about.html" onmouseover="changeImages('selecto_05', 'images/selecto_05-over.gif'); return true;" onmouseout="changeImages('selecto_05', 'images/selecto_05.gif'); return true;"><img name="selecto_05" SRC="images/selecto_05.gif" width=100 height=29 border=0 alt="about"></a></td>
 <td bgcolor="white" valign="top" align="right"><img src="images/skunkWEB1_08.gif" width=171 height=29 border="0" alt="."></td>
 </tr>
 <tr>
  <td valign="top" width="100" bgcolor="white">
   <table width=100 border=0 cellpadding=0 cellspacing=0>
    <tr>
     <td><a href="docs.html" onmouseover="changeImages('selecto_09', 'images/selecto_09-over.gif', 'selecto_13', 'images/selecto_13-selecto_09_over.gif'); return true;" onmouseout="changeImages('selecto_09', 'images/selecto_09.gif', 'selecto_13', 'images/selecto_13.gif'); return true;"><img name="selecto_09" src="images/selecto_09.gif" width=100 height=28 border=0 alt="docs"></a></td>
   </tr>
   <tr>
    <td><a href="download.html" onmouseover="changeImages('selecto_13', 'images/selecto_13-over.gif'); return true;" onmouseout="changeImages('selecto_13', 'images/selecto_13.gif'); return true;"><img name="selecto_13" src="images/selecto_13.gif" width=100 height=30 border=0 alt="download"></a></td>
  </tr>
  <tr>
   <td><a href="mlist.html" onmouseover="changeImages('selecto_17', 'images/selecto_17-over.gif', 'selecto_21', 'images/selecto_21-selecto_17_over.gif'); return true;" onmouseout="changeImages('selecto_17', 'images/selecto_17.gif', 'selecto_21', 'images/selecto_21.gif'); return true;"><img name="selecto_17" src="images/selecto_17.gif" width=100 height=28 border=0 alt="mailing list"></a></td>
						</tr>
						<tr>
							<td><a href="index.html" onmouseover="changeImages('selecto_21', 'images/selecto_21-over.gif', 'selecto_25', 'images/selecto_25-selecto_21_over.gif'); return true;" onmouseout="changeImages('selecto_21', 'images/selecto_21.gif', 'selecto_25', 'images/selecto_25.gif'); return true;"><img name="selecto_21" src="images/selecto_21.gif" width=100 height=29 border=0 alt="news"></a></td>
						</tr>
						<tr>
							<td><a href="cvs.html" onmouseover="changeImages('selecto_25', 'images/selecto_25-over.gif', 'selecto_29', 'images/selecto_29-selecto_25_over.gif'); return true;" onmouseout="changeImages('selecto_25', 'images/selecto_25.gif', 'selecto_29', 'images/selecto_29.gif'); return true;"><img name="selecto_25" src="images/selecto_25.gif" width=100 height=28 border=0 alt="CVS"></a></td>
						</tr>
						<tr>
							<td><a href="skunkdav.html" onmouseover="changeImages('selecto_29', 'images/selecto_29-over.gif', 'selecto_33', 'images/selecto_33-selecto_29_over.gif'); return true;" onmouseout="changeImages('selecto_29', 'images/selecto_29.gif', 'selecto_33', 'images/selecto_33.gif'); return true;"><img name="selecto_29" src="images/selecto_29.gif" width=100 height=29 border=0 alt="SkunkDAV"></a></td>
						</tr>
						<tr>
							<td><a href="pydo.html" onmouseover="changeImages('selecto_33', 'images/selecto_33-over.gif'); return true;" onmouseout="changeImages('selecto_33', 'images/selecto_33.gif'); return true;"><img name="selecto_33" src="images/selecto_33.gif" width=100 height=32 border=0 alt="PyDO"></a></td>
						</tr>
						<tr>
							<td><a href="who.html" onmouseover="changeImages('selecto_33', 'images/selecto_33-selecto_37_over.gif', 'selecto_37', 'images/selecto_37-over.gif'); return true;" onmouseout="changeImages('selecto_33', 'images/selecto_33.gif', 'selecto_37', 'images/selecto_37.gif'); return true;"><img name="selecto_37" src="images/selecto_37.gif" width=100 height=27 border=0 alt="who"></a></td>
						</tr>
<tr>
<td> 
Search (Google):<BR>
<form action="http://www.google.com/search">
<input type=text name=q size=10>
<input type=hidden name=domains value="skunkweb.sourceforge.net">
<input type=hidden name=hl value=en>
<input type=hidden name=sitesearch value="skunkweb.sourceforge.net">
<input type="submit" name=btnG value="Search">
</form>
</td>
</tr>

					</table>
					<table border="0" cellpadding="0" cellspacing="0" width="100">
						<tr>
							<td><img src="styles/pixie.gif" width="6" height="6" border="0" alt="+"></td>
							<td><img src="styles/pixie.gif" width="88" height="6" border="0" alt="--------------------------"></td>
							<td><img src="styles/pixie.gif" width="6" height="6" border="0" alt="+"></td>
						</tr>
						<tr>
							<td><img src="styles/pixie.gif" width="6" height="31" border="0" alt="|"></td>
							<td><A href="http://sourceforge.net"> <IMG src="http://sourceforge.net/sflogo.php?group_id=32756" width="88" height="31" border="0" alt="many thanks to SourceForge"></A></td>
							<td><img src="styles/pixie.gif" width="6" height="6" border="0" alt="|"></td>
						</tr>

						<tr>
							<td><img src="styles/pixie.gif" width="6" height="6" border="0" alt="+"></td>
							<td><img src="styles/pixie.gif" width="11" height="6" border="0" alt="--------------------------"></td>
							<td><img src="styles/pixie.gif" width="6" height="6" border="0" alt="+"></td>
						</tr>

					</table>
				</td>
				<td bgcolor="white" valign="top">
					<table cellspacing=0 cellpadding=0 border=0>
						<tr>
							<td width="4%"><img src="styles/pixie.gif" width="28" height="1" border="0"></td>
							<td><img src="styles/pixie.gif" width="350" height="1" border="0"></td>
						</tr>

						<tr>
							<td width="4%"><img src="styles/pixie.gif" width="28" height="1" border="0"></td>
							<td>

<:val `mainframe`:>
<BR><font color=white>---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ---- </font>

       </td>
						</tr>
					</table>
				</td>
			</tr>

			<tr>
				<td colspan="2" bgcolor="WHITE" align="center"><img src="images/smell_white.gif" width="267" height="51" border="0" alt="(smell the power!)"><br><br></td>
			</tr>
		</table>
		<p></p>
		<hr>
	</body>

</html>
